name: "Plugin clone"
description: "Clone the plugin into the appropriate directories"
inputs:
  josm-revision:
    default: ''
    description: JOSM revision to use to build against, '' is current svn head, 'latest' is current latest, 'tested' is current tested, and 'rNUMBER' is for specific revisions
    required: false
  josm-test-revision:
    default: ''
    description: JOSM revision to use to build tests against, '' is current svn head, 'latest' is current latest, 'tested' is current tested, and 'rNUMBER' is for specific revisions
    required: false
  java-version:
    default: '11'
    description: The java version to build JOSM against. This should typically not be changed.
    required: false
  java-distribution:
    default: "temurin"
    description: The java distribution to build JOSM against. This should typically not be changed.
    required: false
  plugin-jar-name:
    default: ${{ github.event.repository.name }}
    description: "The base name for the jar file if it does not match the repository name. Example: josm-foo where the jar is foo.jar would pass foo to this action."
    required: false
  fetch-depth:
    default: '1'
    required: false
    description: "The number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1"

outputs:
  plugin-directory:
    value: $GITHUB_WORKSPACE/josm/plugins/${{ github.event.repository.name }}
    description: The directory that the plugin source code actually got cloned into

runs:
  using: "composite"
  steps:
  - name: Set up JDK ${{ inputs.java-version }}
    uses: actions/setup-java@v3
    with:
      java-version: ${{ inputs.java-version }}
      distribution: ${{ inputs.java-distribution }}

  - name: Clone JOSM plugin directories
    id: josm-plugin-clone
    uses: JOSM/JOSMPluginAction/actions/josm_plugin_clone@v1

  - uses: actions/checkout@v3
    with:
      path: ${{ steps.josm-plugin-clone.outputs.plugin-dir }}/${{ github.event.repository.name }}
      fetch-depth: ${{ inputs.fetch-depth }}
  - name: Get plugin dependencies
    uses: JOSM/JOSMPluginAction/actions/josm_plugin_dependencies@v1
    with:
      plugin-dir: ${{ steps.josm-plugin-clone.outputs.plugin-dir }}/${{ github.event.repository.name }}
      josm-revision: ${{ inputs.josm-revision }}
      josm-test-revision: ${{ inputs.josm-test-revision }}
      plugin-jar-name: ${{ inputs.plugin-jar-name }}
