on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write
  packages: write

jobs:
  call-workflow-latest:
    uses: JOSM/JOSMPluginAction/.github/workflows/internal_ant.yml@main
    with:
      josm-revision: ""
      java-version: 17
  call-workflow-min:
    uses: JOSM/JOSMPluginAction/.github/workflows/internal_ant.yml@main
    with:
      josm-revision: "r19387"
      java-version: 17
      perform-revision-tagging: false
      repository: 'JOSM/Mapillary'
      ref: 'master'
